default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        name: Run type checks
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
        language: python
        language_version: python3
        types: [python]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
        language: python
        language_version: python3
        types: [python]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--safe, --quiet, --]
        language: python
        language_version: python3
        types: [python]
  - repo: local
    hooks:
      - id: pylint
        name: check pylint
        entry: bash -c "poetry run pylint_runner"
        args:
          - --rcfile=.pylintrc
        language: python
        language_version: python3
        types: [python]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --ini=.bandit
        language: python
        language_version: python3
        types: [python]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        language: python
        language_version: python3
        types: [python]
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        exclude: static
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
        language: python
        language_version: python3
        types: [python]
  - repo: local
    hooks:
    - id: migrations-check
      name: Check for uncreated migrations.
      entry: bash -c "python manage.py makemigrations --check --dry-run"
      language: python
      language_version: python3
      types: [python]
      pass_filenames: false
  - repo: local
    hooks:
    - id: tests
      name: Run tests.
      entry: bash -c "poetry run pytest -n auto"
      language: python
      language_version: python3
      types: [python]
      pass_filenames: false
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]